host: "localhost"
url: "https://simonesilvestroni.com"
canonical_url: "https://simonesilvestroni.com"
lang: "en-GB"
title: "Simone Silvestroni"
description: 'Hey! I’m Simone, a seasoned web designer and developer based in Cambridge, UK. I’ve been designing and coding <strong>accessible and performant websites</strong> since 1998, using HTML, CSS, PHP, WordPress, and now Jekyll and Jamstack. Trading as <strong>Minutes to Midnight</strong>.'
logo: 
  url: "/assets/img/minutestomidnight-glyph.svg"
  alt: "Minutes to Midnight glyph logo"
  width: 180
  height: 180

# -------------------
# Exclusions
# -------------------
exclude:
  - README.md

# -------------------
# Inclusions
# -------------------
include: ["_redirects"]

# -------------------
# SEO
# -------------------
timezone: Europe/Berlin
keywords:
  simone silvestroni,
  web design,
  web development,
  sound design,
  front-end,
  ux,
  user experience,
  jekyll,
  wordpress,
  jamstack,
  html,
  css

defaults:
  - scope:
      path: ""
    values:
      layout: "default"